SELECTED_FEATURES:
  - id
  - phones_per_capita
  - inst_max
  - dependency
  - age_sum
  - age_min
  - age_max
  - house_structure_score
  - escolari_max
  - age_std
  - rooms_per_capita
  - tech_min
  - tech_sum
  - inst_range_
  - dis_min
  - dis_max
  - dis_sum
  - mobilephone_min
  - mobilephone_std
  - mobilephone_range_
  - v18q_min
  - v18q_sum
  - v18q_count
  - female_min
  - female_max
  - female_sum
  - female_std

SELECTED_FEATURES_RENAME_MAPPING:
  id: cifidnbr
  phones_per_capita: age_segment
  inst_max: segment
  dependency: ulprem
  age_sum: etrs_assets
  age_min: w_hlth_mng_wearable_indx
  age_max: w_hlth_ins_direct_pay_indx
  house_structure_score: hhetrs_assets
  escolari_max: w_short_term_loan_indx
  age_std: totprem
  rooms_per_capita: hhprem
  tech_min: w_ins_medsup_buyer_indx
  tech_sum: hh_aua
  inst_range_: hhsa
  dis_min: totsa
  dis_max: hhyrspurch
  dis_sum: w_aggrgt_zip4_home_value
  mobilephone_min: hhpropassets
  mobilephone_std: w_census_pct_white_collar
  mobilephone_range_: pct_cvlsa_totsa
  v18q_min: w_census_median_hh_buying_inc
  v18q_sum: w_census_median_hh_inc
  v18q_count: w_census_median_home_value
  female_min: yearsmember
  female_max: propassets
  female_sum: netasset
  female(std: tot_aum_per_yrmbr
  target: "long_term_care_responder"

  OUTCOME_VARIABLE: "long_term_care_responder"