# id variables
CLIENT_UNIQUE_IDENTIFER:
  - "Id"
  - "idhogar"

# Target variable
TARGET_VAR: "Target"

# Continuous variables at the household level
HH_CONT_VARS:
  - "v2a1"
  - "dependency"
  - "edjefe"
  - "edjefa"
  - "meaneduc"
  - "overcrowding"

# Ordinal variables at the household level
HH_ORDINAL_VARS:
  - "rooms"
  - "r4h1"
  - "r4h2"
  - "r4h3"
  - "r4m1"
  - "r4m2"
  - "r4m3"
  - "r4t1"
  - "r4t2"
  - "r4t3"
  - "v18q1"
  - "tamhog"
  - "tamviv"
  - "hhsize"
  - "hogar_nin"
  - "hogar_adul"
  - "hogar_mayor"
  - "hogar_total"
  - "bedrooms"
  - "qmobilephone"

# Boolean variables at the household level
HH_BOOL_VARS:
  - "hacdor"
  - "hacapo"
  - "v14a"
  - "refrig"
  - "paredblolad"
  - "paredzocalo"
  - "paredpreb"
  - "pisocemento"
  - "pareddes"
  - "paredmad"
  - "paredzinc"
  - "paredfibras"
  - "paredother"
  - "pisomoscer"
  - "pisoother"
  - "pisonatur"
  - "pisonotiene"
  - "pisomadera"
  - "techozinc"
  - "techoentrepiso"
  - "techocane"
  - "techootro"
  - "cielorazo"
  - "abastaguadentro"
  - "abastaguafuera"
  - "abastaguano"
  - "public"
  - "planpri"
  - "noelec"
  - "coopele"
  - "sanitario1"
  - "sanitario2"
  - "sanitario3"
  - "sanitario5"
  - "sanitario6"
  - "energcocinar1"
  - "energcocinar2"
  - "energcocinar3"
  - "energcocinar4"
  - "elimbasu1"
  - "elimbasu2"
  - "elimbasu3"
  - "elimbasu4"
  - "elimbasu5"
  - "elimbasu6"
  - "epared1"
  - "epared2"
  - "epared3"
  - "etecho1"
  - "etecho2"
  - "etecho3"
  - "eviv1"
  - "eviv2"
  - "eviv3"
  - "tipovivi1"
  - "tipovivi2"
  - "tipovivi3"
  - "tipovivi4"
  - "tipovivi5"
  - "computer"
  - "television"
  - "lugar1"
  - "lugar2"
  - "lugar3"
  - "lugar4"
  - "lugar5"
  - "lugar6"
  - "area1"
  - "area2"
  - "v2a1_missing"

# Redundant variables at the household level
REDUNDANT_HH_VARS:
  - "tamhog"
  - "hogar_total"
  - "r4t3"

# boolean variables at the individual level
IND_BOOL_VARS:
  - "v18q"
  - "dis"
  - "male"
  - "female"
  - "estadocivil1"
  - "estadocivil2"
  - "estadocivil3"
  - "estadocivil4"
  - "estadocivil5"
  - "estadocivil6"
  - "estadocivil7"
  - "parentesco1"
  - "parentesco2"
  - "parentesco3"
  - "parentesco4"
  - "parentesco5"
  - "parentesco6"
  - "parentesco7"
  - "parentesco8"
  - "parentesco9"
  - "parentesco10"
  - "parentesco11"
  - "parentesco12"
  - "instlevel1"
  - "instlevel2"
  - "instlevel3"
  - "instlevel4"
  - "instlevel5"
  - "instlevel6"
  - "instlevel7"
  - "instlevel8"
  - "instlevel9"
  - "mobilephone"

# Ordinal variables at the individual level
IND_ORDINAL_VARS:
  - "rez_esc"
  - "escolari"
  - "age"

# Squared variables
SQUARED_VARS:
  - "SQBescolari"
  - "SQBage"
  - "SQBhogar_total"
  - "SQBedjefe"
  - "SQBhogar_nin"
  - "SQBovercrowding"
  - "SQBdependency"
  - "SQBmeaned"
  - "agesq"

# Aggregated features (from individual features) that are selected
SELECTED_IND_AGGREGATED_FEATURES:
  - "v18q-min"
  - "v18q-sum"
  - "v18q-count"
  - "v18q-std"
  - "v18q-range_"
  - "dis-min"
  - "dis-max"
  - "dis-sum"
  - "female-min"
  - "female-max"
  - "female-sum"
  - "female-std"
  - "female-range_"
  - "estadocivil1-min"
  - "estadocivil1-max"
  - "estadocivil1-sum"
  - "estadocivil2-min"
  - "estadocivil2-max"
  - "estadocivil2-std"
  - "estadocivil3-min"
  - "estadocivil3-max"
  - "estadocivil3-std"
  - "estadocivil4-min"
  - "estadocivil4-max"
  - "estadocivil5-min"
  - "estadocivil5-max"
  - "estadocivil5-sum"
  - "estadocivil6-min"
  - "estadocivil6-max"
  - "estadocivil7-min"
  - "estadocivil7-max"
  - "estadocivil7-sum"
  - "estadocivil7-std"
  - "parentesco1-min"
  - "parentesco1-max"
  - "parentesco1-std"
  - "parentesco2-min"
  - "parentesco2-max"
  - "parentesco2-std"
  - "parentesco3-min"
  - "parentesco3-max"
  - "parentesco3-sum"
  - "parentesco4-min"
  - "parentesco4-max"
  - "parentesco4-sum"
  - "parentesco5-min"
  - "parentesco5-max"
  - "parentesco6-min"
  - "parentesco6-max"
  - "parentesco6-sum"
  - "parentesco7-min"
  - "parentesco7-max"
  - "parentesco8-min"
  - "parentesco8-max"
  - "parentesco9-min"
  - "parentesco9-max"
  - "parentesco9-sum"
  - "parentesco10-min"
  - "parentesco10-max"
  - "parentesco11-min"
  - "parentesco11-max"
  - "parentesco11-sum"
  - "parentesco12-min"
  - "parentesco12-max"
  - "parentesco12-sum"
  - "instlevel1-min"
  - "instlevel1-max"
  - "instlevel1-sum"
  - "instlevel2-min"
  - "instlevel2-max"
  - "instlevel2-sum"
  - "instlevel2-std"
  - "instlevel3-min"
  - "instlevel3-max"
  - "instlevel3-sum"
  - "instlevel3-std"
  - "instlevel4-min"
  - "instlevel4-max"
  - "instlevel4-sum"
  - "instlevel4-std"
  - "instlevel5-min"
  - "instlevel5-max"
  - "instlevel5-sum"
  - "instlevel6-min"
  - "instlevel6-max"
  - "instlevel7-min"
  - "instlevel7-max"
  - "instlevel8-min"
  - "instlevel8-max"
  - "instlevel8-sum"
  - "instlevel8-std"
  - "instlevel9-min"
  - "instlevel9-max"
  - "mobilephone-min"
  - "mobilephone-std"
  - "mobilephone-range_"
  - "rez_esc-min"
  - "rez_esc-max"
  - "escolari-min"
  - "escolari-max"
  - "escolari-sum"
  - "escolari-std"
  - "escolari-range_"
  - "age-min"
  - "age-max"
  - "age-sum"
  - "age-std"
  - "age-range_"
  - "inst-max"
  - "inst-std"
  - "inst-range_"
  - "escolari_normalized_by_age-min"
  - "escolari_normalized_by_age-max"
  - "escolari_normalized_by_age-sum"
  - "escolari_normalized_by_age-std"
  - "escolari_normalized_by_age-range_"
  - "inst_normalized_by_age-max"
  - "inst_normalized_by_age-std"
  - "inst_normalized_by_age-range_"
  - "tech-min"
  - "tech-sum"
  - "tech-std"
  - "tech-range_"


