# Perform static checks on CI/CD workflow files using actionlint

name: Lint CI/CD workflow files
on:
  pull_request:
    paths:
      - '.github/workflows/**'
  workflow_dispatch:
  push:
    branches:
      - feature/DASC-1827
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
