name: Feature and Training Unit and Integration Tests for my_mlops_project
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/ptb-ltc-project-ci.yml'

defaults:
  run:
    working-directory: ./

env:
  DATABRICKS_TOKEN: ${{ secrets.STAGING_WORKSPACE_TOKEN }}

concurrency: ptb-ltc-feature-training-integration-test-staging

jobs:
  integration_test:
    runs-on:
      group: linux-runners
      labels: [self-hosted, linux]
    container:
      image: ${{ vars.IMAGE_REGISTRY_PULL }}/docker-mlops/mlops:latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: databricks/setup-cli@v0.221.0
      - name: Validate Bundle For Test Deployment Target in Staging Workspace
        id: validate
        run: |
          databricks bundle validate -t test
      - name: Deploy Bundle to Test Deployment Target in Staging Workspace
        id: deploy
        run: |
          databricks bundle deploy -t test
      - name: Run Feature Engineering Workflow for Test Deployment Target in Staging Workspace
        id: feature_pipeline
        run: |
          databricks bundle run feature_pipeline_job -t test
      - name: Run Training Workflow for Test Deployment Target in Staging Workspace
        id: training
        run: |
          databricks bundle run train_pipeline_job -t test



  #unit_tests:
  #  runs-on:
  #    group: linux-runners
  #    labels: [self-hosted, linux]
  #  container:
  #  permissions:
  #    id-token: write
  #    contents: write
  #  steps:
  #    - uses: actions/checkout@v4
  #    - uses: actions/setup-python@v5
  #      with:
  #        python-version: 3.10
  #    # Feature store tests bring up a local Spark session, so Java is required.
  #    - uses: actions/setup-java@v4
  #      with:
  #        distribution: 'temurin'
  #        java-version: '11'
  #    - name: Install dependencies
  #      run: |
  #          python -m pip install --upgrade pip
  #          pip install -r requirements.txt
  #          pip install -r ../test-requirements.txt
  #    - name: Run tests with pytest
  #      run: |
  #          pytest
